p=float(input("Enter the Principal Amount -> "))
si=float(input("Enter the Interest Amount ->"))
t=float(input("Enter the Time Period (in years) -> "))
r=(si*100)/(p*t)
print("The rate of interest of given values is -> %.2f"%(r))
